version: '3'

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - '15432:5432'
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=10", "-c", "superuser_reserved_connections=1"]
    networks:
      - test-network-go-sqlc-migrations-tests

networks:
  test-network-go-sqlc-migrations-tests:
