// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: articles.sql

package sqlc_models

import (
	"context"
)

const articlesGetAll = `-- name: ArticlesGetAll :many
SELECT id, title, created_at FROM articles
`

func (q *Queries) ArticlesGetAll(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, articlesGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
