// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc_models

import (
	"time"
)

type Article struct {
	ID        int32
	Title     string
	CreatedAt time.Time
}

type Author struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt time.Time
}
